apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
  namespace: {{ .Values.global.namespace | required "A global namespace must be defined in your values file!" }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.userAssignedIdentityID }}
