name: notification
replicaCount: 2
rollingUpdate:
  type: RollingUpdate
  maxUnavailable: 25%
  maxSurge: 25%

image:
  name: maheshnandi/organistation-notification
  tag: v1.0.0
  pullPolicy: Always

service:
  port: 8007
  targetPort: 8007
  healthPath: /health

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

secrets:
  - name: "SERVICE-BUS-NAMESPACE"
    key: "SERVICE_BUS_NAMESPACE"
  - name: "ACS-CONNECTION-STRING"
    key: "ACS_CONNECTION_STRING"
  - name: "SIGNALR-CONNECTION-STRING"
    key: "SIGNALR_CONNECTION_STRING"
  - name: "JWT-SECRET"
    key: "JWT_SECRET"
