name: gateway
replicaCount: 2
rollingUpdate:
  type: RollingUpdate
  maxUnavailable: 25%
  maxSurge: 25%

image:
  name: maheshnandi/organistation-gateway
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  port: 3000
  targetPort: 3000
  healthPath: /api/health

env:
  - name: AUTH_SERVICE_URL
    value: "http://auth:80"
  - name: AI_SERVICE_URL
    value: "http://ai:80"
  - name: HR_SERVICE_URL
    value: "http://hr:80"
  - name: PROJECT_SERVICE_URL
    value: "http://projects:80"
  - name: FINANCE_SERVICE_URL
    value: "http://finance:80"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

secrets:
  - name: "JWT-SECRET"
    key: "JWT_SECRET"
  - name: "INTERNAL-SERVICE-SECRET"
    key: "INTERNAL_SERVICE_SECRET"

serviceUrls:
  authPort: 8001
  aiPort: 8000
  hrPort: 8002
  projectsPort: 8003
  financePort: 8004
